### ISSUE TITLE
How long does it take to train the networks?

### ISSUE THREAD

**Issue by Qianqian3764** [xxlong0/CNMNet#7]
Hi, thanks for your code and paper.
I want to ask you one thing.
How many days does it take for training network？

**Comment by xxlong0** [comment]
About 3~4 days on RTX 2080 Ti.
________________________________
发件人: Haif ***@***.***>
发送时间: 2022年9月8日 23:05
收件人: xxlong0/CNMNet ***@***.***>
抄送: Subscribed ***@***.***>
主题: [xxlong0/CNMNet] How long does it take to train the networks? (Issue #7)


Hi, thanks for your code and paper.
I want to ask you one thing.
How many days does it take for training network？

―
